import HomeComponent from "@/components/HomeComponents";
import axios from "axios";
import React from "react";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default async function Home() {
  const {data} = await axios.get("https://fakestoreapi.com/products");

  return <HomeComponent data={data} />;
}
